import type { Locale } from '../i18n/locales';
import type { UiStrings } from '../i18n/types';
export const workbenchStrings: Record<Locale, UiStrings['workbench']> = {
  ja: {
    input: '入力', choose: 'アーカイブを選択', busy: '処理中です。完了後に入力してください。', single: '1つのアーカイブを選んでください。',
    large: '入力は1 GB（1,000,000,000 bytes）以下にしてください。', unknown: '形式を確認できません。ZIP、RAR、7z、tar を選んでください。',
    source: '入力ファイル', browse: '閲覧', extract: '取り出し', entries: '総エントリ数', files: 'ファイル数', eligible: '抽出可能件数',
    name: '名前', size: 'サイズ', previous: '前へ', next: '次へ', page: 'ページ', all: '全件', one: '1件', chooseOne: '取り出し対象に選ぶ', run: '取り出す',
    results: '結果', save: '保存', saveFile: 'ファイルを保存', reinput: 'この結果を次の入力にする', reinputFile: '次の入力にする', count: '件', listingError: '一覧の取得に失敗しました。',
    jobError: '取り出しに失敗しました。再実行できます。', encrypted: '暗号化ファイルとディレクトリは全件取り出しから除外されます。',
    duplicate: '同名の項目は、1件取り出しで最初の一致が使われます。', reset: 'リセット', progress: '進捗',
    remove: '削除', 'fix-names': '名前修復', removeGuide: 'チェックを外した項目を新しい ZIP から除外します。元の入力は変わりません。',
    keep: '残す', keepAll: '現在の入力のすべての項目を残す', clearAll: '現在の入力のすべての項目を除外対象にする', duplicateKeep: '同名項目はまとめて残すか除外します。',
    plannedRemove: '除外予定', keptFiles: '残すファイル', entriesUnit: '件（ディレクトリを含む）', filesUnit: 'ファイル',
    emptyKeep: '少なくとも1ファイルを残してください。', removeRun: '新しい ZIP を作る', repairRun: '名前を修復して新しい ZIP を作る',
    repairGuide: '文字化けの可能性がある名前を Shift_JIS として読み直した候補です。プレビューを確認してください。',
    repairBefore: '修復前', repairAfter: '修復後', plannedRepair: '修復対象', collision: '同名衝突のため実行できません: ',
    orderGuide: '名前修復を先に確認してください。削除による再構築では名前が UTF-8 化され、後から修復できるとは限りません。',
    goRepair: '名前修復を確認', removed: '除外', kept: '残り', repaired: '修復', processingEntry: '処理中の項目', retryListing: '一覧を再試行',
    listingZip: 'ZIP の識別子があります。開けない ZIP から内容を救出する機能は今後追加予定です。名前修復とは別の機能です。',
    listingArchive: 'RAR／7z の取り出しは一覧を取得できた後に利用できます。このファイルの一覧を再試行できます。',
    listingTar: '一覧取得を再試行できます。', listingUnknown: '形式を確認できません。別の入力を選んでください。',
    'wrong-password': 'パスワードを使って読み出せませんでした。パスワードが正しくないか、暗号化データを読み取れません。',
    'encrypted-entry': 'この操作では暗号化された項目を処理できません。', 'bad-central': 'ZIP の一覧情報を読み取れませんでした。',
    'too-large': '入力は1 GB（1,000,000,000 bytes）以下にしてください。', unsupported: 'この形式または操作には対応していないか、このアーカイブを読み取れません。',
    'not-encrypted': '暗号化された項目が見つかりませんでした。', aborted: '処理が中断されました。', genericInput: '入力を読み取れませんでした。',
    genericListing: '一覧を取得できませんでした。', genericJob: '操作に失敗しました。再実行できます。',
    removeEncrypted: '暗号化された項目を残す選択になっています。対象を除外して再実行できます。',
    repairEncrypted: 'この画面ではパスワードを使った再構築を扱いません。', encryptedKept: '暗号化された項目が残る場合、再構築は失敗します。',
  },
  en: {
    input: 'Input', choose: 'Choose an archive', busy: 'Processing. Try another input when it finishes.', single: 'Choose one archive.',
    large: 'Choose an input of 1 GB (1,000,000,000 bytes) or less.', unknown: 'Format could not be identified. Choose ZIP, RAR, 7z, or tar.',
    source: 'Source file', browse: 'Browse', extract: 'Extract', entries: 'Total entries', files: 'Files', eligible: 'Extractable files',
    name: 'Name', size: 'Size', previous: 'Previous', next: 'Next', page: 'Page', all: 'All', one: 'One', chooseOne: 'Select for extraction', run: 'Extract',
    results: 'Results', save: 'Save', saveFile: 'Save file', reinput: 'Use this result as the next input', reinputFile: 'Use as next input', count: ' files', listingError: 'Could not list this archive.',
    jobError: 'Extraction failed. You can retry.', encrypted: 'Encrypted files and directories are excluded from Extract all.',
    duplicate: 'For duplicate names, Extract one uses the first match.', reset: 'Reset', progress: 'Progress',
    remove: 'Remove', 'fix-names': 'Repair names', removeGuide: 'Unchecked entries are excluded from the new ZIP. The source stays unchanged.',
    keep: 'Keep', keepAll: 'Keep all entries in the current input', clearAll: 'Exclude all entries in the current input', duplicateKeep: 'Entries with the same name share one choice.',
    plannedRemove: 'Planned exclusions', keptFiles: 'Files kept', entriesUnit: ' entries (including directories)', filesUnit: ' files',
    emptyKeep: 'Keep at least one file.', removeRun: 'Create new ZIP', repairRun: 'Repair names into a new ZIP',
    repairGuide: 'These names may be garbled. Review the candidates decoded as Shift_JIS before running.',
    repairBefore: 'Before', repairAfter: 'Candidate', plannedRepair: 'Repair targets', collision: 'Name collision prevents this operation: ',
    orderGuide: 'Check name repair first. Removal rewrites names as UTF-8, so later repair may not be possible.',
    goRepair: 'Review name repair', removed: 'Excluded', kept: 'Remaining', repaired: 'Repaired', processingEntry: 'Processing entry', retryListing: 'Retry listing',
    listingZip: 'A ZIP signature was found. Recovery from an unreadable ZIP is planned separately from name repair.',
    listingArchive: 'RAR/7z extraction is available after a successful listing. You can retry listing this file.', listingTar: 'You can retry listing this archive.',
    listingUnknown: 'The format could not be identified. Choose another input.',
    'wrong-password': 'Could not read the encrypted data with this password. The password may be incorrect, or the encrypted data may be unreadable.',
    'encrypted-entry': 'This operation cannot process encrypted entries.', 'bad-central': 'Could not read the ZIP directory information.',
    'too-large': 'Choose an input of 1 GB (1,000,000,000 bytes) or less.', unsupported: 'This format or operation is unsupported, or this archive could not be read.',
    'not-encrypted': 'No encrypted entries were found.', aborted: 'Processing was interrupted.', genericInput: 'Could not read the input.',
    genericListing: 'Could not list the archive.', genericJob: 'The operation failed. You can retry.',
    removeEncrypted: 'Encrypted entries are selected to remain. Exclude them and retry.', repairEncrypted: 'Password-based rewriting is unavailable on this screen.',
    encryptedKept: 'Rewriting fails if encrypted entries remain.',
  },
};
