import { readFile, readdir, writeFile } from 'node:fs/promises';
import { realpathSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const materialPattern = /^(?:license|licence|copying|notice)(?:[.\-_].*)?$/i;
// These files are copied from public/ unchanged. Their packages cannot appear in Vite maps:
// libarchive.js supplies worker-bundle.js, which contains the Comlink runtime.
const copiedPackages = ['libarchive.js', 'comlink'];

const normalized = (text) => text.replace(/\r\n?/g, '\n').trimEnd() + '\n';
const json = async (path) => JSON.parse(await readFile(path, 'utf8'));

export function packageLocationsFromSources(sources) {
  const locations = new Set();
  for (const source of sources) {
    const parts = source.replaceAll('\\', '/').split('/');
    const first = parts.indexOf('node_modules');
    if (first < 0) continue;
    let end = first + 2;
    for (let i = first + 1; i < parts.length; i++) {
      if (parts[i] === 'node_modules') end = i + (parts[i + 1]?.startsWith('@') ? 3 : 2);
    }
    if (parts[end - 1]?.startsWith('@')) end++;
    const location = parts.slice(first, end).join('/');
    if (location && !location.endsWith('/node_modules')) locations.add(location);
  }
  return [...locations].sort();
}

async function mapSources(dir) {
  const sources = [];
  async function visit(path) {
    for (const entry of await readdir(path, { withFileTypes: true })) {
      const item = join(path, entry.name);
      if (entry.isDirectory()) await visit(item);
      else if (entry.isFile() && entry.name.endsWith('.map')) {
        const map = await json(item);
        if (!Array.isArray(map.sources)) throw new Error(`Invalid sourcemap: ${item}`);
        sources.push(...map.sources);
      }
    }
  }
  await visit(dir);
  return sources;
}

async function packageMaterials(dir) {
  const names = (await readdir(dir)).filter((name) => materialPattern.test(name)).sort();
  return Promise.all(names.map(async (name) => ({ name, text: normalized(await readFile(join(dir, name), 'utf8')) })));
}

export async function generateNotice(root = projectRoot, sources) {
  const discovered = sources ?? await mapSources(join(root, '.notice-build'));
  const fromMaps = packageLocationsFromSources(discovered);
  const project = await json(join(root, 'package.json')).catch(() => ({}));
  const pwaRequired = Boolean(project.devDependencies?.['@vite-pwa/astro']);
  if (pwaRequired && !fromMaps.some(location => location.includes('workbox-'))) {
    throw new Error('Workbox code missing from analysis sourcemaps');
  }
  const explicit = pwaRequired ? [...copiedPackages, 'vite-plugin-pwa'] : copiedPackages;
  const locations = new Set([...fromMaps, ...explicit.map((name) => `node_modules/${name}`)]);
  const packages = new Map();
  for (const location of [...locations].sort()) {
    const dir = join(root, location);
    const actual = await json(join(dir, 'package.json'));
    const expectedName = location.split('/node_modules/').at(-1).replace(/^node_modules\//, '');
    if (actual.name !== expectedName || !actual.version || !actual.license) {
      throw new Error(`Invalid installed package metadata: ${location}`);
    }
    const materials = await packageMaterials(dir);
    if (!materials.length || materials.some((material) => !material.text.trim())) {
      throw new Error(`Missing license text: ${actual.name}@${actual.version}`);
    }
    const key = `${actual.name}@${actual.version}`;
    const previous = packages.get(key);
    if (previous && (previous.license !== actual.license || JSON.stringify(previous.materials) !== JSON.stringify(materials))) {
      throw new Error(`Conflicting installed package: ${key}`);
    }
    packages.set(key, { license: actual.license, materials });
  }
  const sections = [
    '# Third-party notices', '',
    'Generated by `node scripts/gen-notice.mjs`. Do not edit this file directly.',
    'The project source is licensed under MIT; see [LICENSE](LICENSE). The notices below apply to code delivered to the browser.',
    '', '## Browser-delivered npm packages', '',
    'Packages are identified from an analysis build with sourcemaps, plus packages copied unchanged into public assets.', '',
  ];
  for (const key of [...packages.keys()].sort()) {
    const { license, materials } = packages.get(key);
    sections.push(`### ${key}`, '', `- Package license: \`${license}\``, '');
    for (const material of materials) {
      sections.push(`#### ${material.name}`, '', '```text', material.text.trimEnd(), '```', '');
    }
  }
  const wasm = await json(join(root, 'vendor/libarchive-lean/components.json'));
  sections.push('## Lean libarchive WebAssembly build', '',
    'The five matched artifacts in `vendor/libarchive-lean/` replace the npm package distribution files. The build recipe is `wasm/libarchive-lean/Dockerfile`. Version and attribution data are maintained in `vendor/libarchive-lean/components.json`.', '');
  for (const component of wasm.components) {
    if (!component.name || !component.version || !component.spdx || !component.source || !component.copyright || !component.licenseFile) {
      throw new Error(`Incomplete WASM component: ${component.name ?? '(unnamed)'}`);
    }
    sections.push(`### ${component.name} ${component.version}`, '',
      `- License: \`${component.spdx}\``, `- Source: ${component.source}`,
      `- Copyright: ${component.copyright}`, `- Linkage: ${component.linkage}`, '',
      '```text', await wasmLicenseText(root, component), '```', '');
  }
  return sections.join('\n').trimEnd() + '\n';
}

async function wasmLicenseText(root, component) {
  const text = normalized(await readFile(join(root, 'vendor/libarchive-lean/licenses', component.licenseFile), 'utf8')).trimEnd();
  if (!text.trim()) throw new Error(`Empty license text for WASM component: ${component.name}`);
  return text;
}

export async function checkNotice(root, output) {
  const current = await readFile(join(root, 'NOTICE.md'), 'utf8').catch(() => null);
  if (current !== output) throw new Error('NOTICE.md is missing or out of date');
}

if (process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    console.error('Usage: node scripts/gen-notice.mjs [--check]');
    process.exitCode = 1;
  } else {
    try {
      const build = spawnSync(process.execPath, [join(projectRoot, 'node_modules/astro/astro.js'), 'build'], {
        cwd: projectRoot, env: { ...process.env, NOTICE_ANALYZE: '1' }, stdio: 'inherit',
      });
      if (build.error) throw build.error;
      if (build.status !== 0) throw new Error('Analysis build failed');
      const output = await generateNotice();
      if (args[0] === '--check') await checkNotice(projectRoot, output);
      else await writeFile(join(projectRoot, 'NOTICE.md'), output);
    } catch (error) {
      console.error(error.message);
      process.exitCode = 1;
    }
  }
}
