import { createHash } from 'node:crypto';
import { existsSync, lstatSync } from 'node:fs';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const securityHeaders = (hashes) => ({
  'Content-Security-Policy': [
    "default-src 'self'",
    `script-src 'self' 'wasm-unsafe-eval' ${hashes.join(' ')}`.trimEnd(),
    "worker-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' blob: data:",
    "connect-src 'self'",
    "manifest-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ].join('; '),
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  'X-Frame-Options': 'DENY',
});

export function hashesFromHtml(html) {
  const document = new JSDOM(html, { contentType: 'text/html' }).window.document;
  return [...document.querySelectorAll('script')]
    .filter((script) => !script.hasAttribute('src') && script.getAttribute('type')?.trim().toLowerCase() !== 'application/ld+json')
    .map((script) => `'sha256-${createHash('sha256').update(script.textContent, 'utf8').digest('base64')}'`);
}

async function htmlFiles(dir) {
  const files = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...await htmlFiles(path));
    else if (entry.isFile() && entry.name.endsWith('.html')) files.push(path);
  }
  return files.sort();
}

export async function headerModel(root) {
  if (existsSync(join(root, 'public/_headers')) || isSymlink(join(root, 'public/_headers'))) {
    throw new Error('public/_headers must not exist');
  }
  const files = await htmlFiles(join(root, 'dist'));
  if (!files.length) throw new Error('No built HTML found in dist');
  const hashes = new Set();
  for (const file of files) {
    for (const hash of hashesFromHtml(await readFile(file, 'utf8'))) hashes.add(hash);
  }
  return [
    { path: '/*', headers: securityHeaders([...hashes].sort()) },
    { path: '/_astro/*', headers: { 'Cache-Control': 'public, max-age=31536000, immutable' } },
    // Vendor worker and WASM use fixed URLs and must be revalidated as a matched build.
    { path: '/vendor/*', headers: { 'Cache-Control': 'no-cache' } },
    { path: '/sw.js', headers: { 'Cache-Control': 'no-cache' } },
  ];
}

function isSymlink(path) {
  try { return lstatSync(path).isSymbolicLink(); } catch (error) {
    if (error.code === 'ENOENT') return false;
    throw error;
  }
}

export function pagesHeaders(model) {
  const lines = model.flatMap(({ path, headers }) => [path, ...Object.entries(headers).map(([name, value]) => `  ${name}: ${value}`), '']);
  for (const line of lines) {
    if (line.length > 2000) throw new Error('Pages header line exceeds 2000 characters');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function caddyHeaders(model) {
  const lines = ['# Generated by scripts/gen-headers.mjs.'];
  for (const { path, headers } of model) {
    lines.push(path === '/*' ? 'header {' : `header ${path} {`);
    for (const [name, value] of Object.entries(headers)) lines.push(`  ${name} ${JSON.stringify(value)}`);
    lines.push('}');
  }
  return `${lines.join('\n')}\n`;
}

export async function generateHeaders(root = projectRoot, check = false) {
  const model = await headerModel(root);
  const outputs = [
    [join(root, 'dist/_headers'), pagesHeaders(model)],
    [join(root, 'docker/headers.caddy'), caddyHeaders(model)],
  ];
  if (check) {
    for (const [path, expected] of outputs) {
      const actual = await readFile(path, 'utf8').catch((error) => {
        if (error.code === 'ENOENT') return null;
        throw error;
      });
      if (actual !== expected) throw new Error(`${path} is missing or out of date`);
    }
  } else {
    for (const [path, output] of outputs) await writeFile(path, output);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    console.error('Usage: node scripts/gen-headers.mjs [--check]');
    process.exitCode = 1;
  } else {
    try { await generateHeaders(projectRoot, args[0] === '--check'); }
    catch (error) { console.error(error.message); process.exitCode = 1; }
  }
}
